---
title: "P8105 Homework 2"
author: "Maria Serafini"
date: "10/1/2025"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```


## Problem 1 

Import and clean `pols_month_df`

```{r}
pols_month_df <- 
  read.csv("data/pols-month.csv", na = c("NA", "")) |> 
  janitor::clean_names() |> 
  separate(
    mon, into = c("year", "month", "day")) |> 
  mutate(
    month = case_match(
      month, 
      "01" ~ "January",
      "02" ~ "February",
      "03" ~ "March",
      "04" ~ "April", 
      "05" ~ "May", 
      "06" ~ "June", 
      "07" ~ "July", 
      "08" ~ "August", 
      "09" ~ "September", 
      "10" ~ "October", 
      "11" ~ "November", 
      "12" ~ "December"), 
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem")
    ) |> 
  select(-prez_gop, -prez_dem, -day)
```

Import and clean `snp.csv`

```{r}
snp_df <-
  read.csv("data/snp.csv", na = c("NA", "")) |> 
  janitor::clean_names() |> 
  mutate(
    date = mdy(date))|> 
  separate(
    date, into = c("year", "month", "day")) |>
  mutate(
    month = case_match(
      month, 
      "01" ~ "January",
      "02" ~ "February",
      "03" ~ "March",
      "04" ~ "April", 
      "05" ~ "May", 
      "06" ~ "June", 
      "07" ~ "July", 
      "08" ~ "August", 
      "09" ~ "September", 
      "10" ~ "October", 
      "11" ~ "November", 
      "12" ~ "December")
  ) |> 
  select(-day)
```


